GitHub Actions: update Arch Linux keyring
https://github.com/fishilico/arch-selinux/runs/7590664112?check_suite_focus=true
failed with:

    checking keyring...
    downloading required keys...
    :: Import PGP key 139B09DA5BF0D338, "David Runge <dvzrv@archlinux.org>"? [Y/n]
    checking package integrity...
    error: libcap: signature from "David Runge <dvzrv@archlinux.org>"
    is marginal trust
    :: File /mnt/var/cache/pacman/pkg/libcap-2.65-1-x86_64.pkg.tar.zst
    is corrupted (invalid or corrupted package (PGP signature)).
    error: failed to commit transaction (invalid or corrupted package)

This is because the key was recently added. Add `pacman -Sy
archlinux-keyring` to update the keyring. This requires removing
"CheckSpace"  from pacman config because pacman does not like it:

    error: could not determine cachedir mount point /var/cache/pacman/pkg
    error: failed to commit transaction (not enough free disk space)

And remove this package from the cache, overwise `repo-add` fails.