build_and_install_all: install util-linux-selinux before building systemd
Since https://github.com/systemd/systemd/pull/17780, systemd-selinux
(248.3-2) cannot be built with util-linux-libs 2.37 and
util-linux-selinux 2.36. More precisely, the header files for util-linux
has to be in sync with the libs, otherwise this error happens:

    ../systemd-stable/src/udev/udev-builtin-blkid.c: In function ‘builtin_blkid’:
    ../systemd-stable/src/udev/udev-builtin-blkid.c:262:29: error:
    implicit declaration of function ‘blkid_probe_set_hint’; did you
    mean ‘blkid_probe_get_size’? [-Werror=implicit-function-declaration]
      262 |                         r = blkid_probe_set_hint(pr, optarg, 0);
          |                             ^~~~~~~~~~~~~~~~~~~~
          |                             blkid_probe_get_size

    ../systemd-stable/src/udev/udev-builtin-blkid.c:262:29: warning:
    nested extern declaration of ‘blkid_probe_set_hint’ [-Wnested-externs]

    cc1: some warnings being treated as errors
    [344/2017] Linking target src/shared/libsystemd-shared-248.so
    ninja: build stopped: subcommand failed.

Fix this by installing util-linux-selinux with util-linux-libs-selinux
before building systemd-selinux.